### ISSUE TITLE
Fix security vulnerabilities

### ISSUE THREAD

**Issue by BAndiT1983** [apertus-open-source-cinema/web-remote#6]
Packages have to be reviewed, either versions updated or new dependencies added directly to package.json, if original package is not up to date.

**Comment by sp-apertus** [comment]
I assume this is because of:


  | apertus-open-source-cinema/web-remote
-- | --
Known  high severity security vulnerability detected in tar < 4.4.2 defined in package-lock.json.                                                                                                                                                                                                                   package-lock.json update suggested: tar ~> 4.4.2. | Known  high severity security vulnerability detected in tar < 4.4.2 defined in package-lock.json. | package-lock.json update suggested: tar ~> 4.4.2.
Known  high severity security vulnerability detected in tar < 4.4.2 defined in package-lock.json.
package-lock.json update suggested: tar ~> 4.4.2.

**Comment by BAndiT1983** [comment]
https://github.com/apertus-open-source-cinema/web-remote/commit/58c28379c36d927b49ec962a4335592b68261be7#commitcomment-33430937
